### PR TITLE
Go modules turnerlabs

### PR DESCRIPTION
**Pull request by bdharris08**
REF: https://github.com/turnerlabs/fargate-create/issues/37

Proposal:
Switch to using go modules.

If using Go 1.18, we can use this to install:
```
go install github.com/turnerlabs/fargate-create@latest
```

### CODE REVIEW

**Comment by awlawl** [comment]
Thanks for the contribution, I will try to get this reviewed this week. 

I assume you are not an employee of Warner Media/Warner Bros Discovery, correct?

**Comment by bdharris08** [comment]
Correct.

**Review by awlawl — APPROVED** [review]
I was able to build using the new system with go 1.18.1. I verified on a Monterey system that the original binary was crashing and that a new build works.

We are just about to roll out a new way for outside contributors to contribute to our open source projects. When that is ready I will let you know and then I can merge.

Thanks again

**Comment by awlawl** [comment]
@bdharris08 

So we have our open source agreement working. It will create a line in the PR "Checks" section that you will need to click on, read and then agree to.

Unfortunately since we didn't have turned on for this repo when you submitted, you might have to resubmit the PR. If thats the case: Push it up again, open a new PR, Agree to the terms and I will merge asap.

Sorry to make you do this, we just rolled out this process this week so you might be one of the first to contribute.

**Comment by bdharris08** [comment]
@awlawl That's ok, I submitted this PR to be helpful. It can be easily re-created by your team as per your earlier comment. I'll go ahead and close this and leave the change for your team to implement.
You can find more information about go modules here: https://go.dev/blog/migrating-to-go-modules

**Comment by awlawl** [comment]
Thank you for your help!

**Pull request closed without merging**
